//go:build linux && shukrabpf

// Package bpfgen loads CO-RE collections produced by bpf2go.
// Each program attaches on its own. A missing KVM tracepoint does not stop the others.
package bpfgen

import (
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Status is one program's attach result. observe maps this onto the API.
type Status struct {
	Name   string
	Status string
	Detail string
}

// Attach loads every embedded collection. LoadKvm and the other loaders are
// generated by `make generate` into this package (bpf2go exports them).
func Attach() ([]Status, error) {
	return []Status{
		try("kvm", LoadKvm),
		try("sched", LoadSched),
		try("block", LoadBlock),
		try("net", LoadNet),
	}, nil
}

// pinnedColls and pinnedLinks stay referenced for the process lifetime.
// Dropping them closes the programs and the hooks detach immediately.
var (
	pinnedColls []*ebpf.Collection
	pinnedLinks []link.Link
)

type specFunc func() (*ebpf.CollectionSpec, error)

func try(name string, load specFunc) Status {
	spec, err := load()
	if err != nil {
		return Status{Name: name, Status: "missing", Detail: err.Error()}
	}
	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		return Status{Name: name, Status: "detached", Detail: err.Error()}
	}
	pinnedColls = append(pinnedColls, coll)
	var attached, total int
	var last error
	for progName, specProg := range spec.Programs {
		total++
		prog := coll.Programs[progName]
		if prog == nil {
			last = fmt.Errorf("%s missing from collection", progName)
			continue
		}
		if err := attachSection(specProg.SectionName, prog); err != nil {
			last = fmt.Errorf("%s: %w", specProg.SectionName, err)
			continue
		}
		attached++
	}
	if attached == 0 {
		detail := "no hooks attached"
		if last != nil {
			detail = last.Error()
		}
		return Status{Name: name, Status: "detached", Detail: detail}
	}
	if last != nil {
		return Status{Name: name, Status: "attached", Detail: fmt.Sprintf("%d/%d hooks; %v", attached, total, last)}
	}
	return Status{Name: name, Status: "attached", Detail: fmt.Sprintf("%d hooks", attached)}
}

func attachSection(section string, prog *ebpf.Program) error {
	var l link.Link
	var err error
	const tp = "tracepoint/"
	if len(section) > len(tp) && section[:len(tp)] == tp {
		rest := section[len(tp):]
		for i := 0; i < len(rest); i++ {
			if rest[i] == '/' {
				l, err = link.Tracepoint(rest[:i], rest[i+1:], prog, nil)
				break
			}
		}
		if l == nil && err == nil {
			return fmt.Errorf("unsupported section %s", section)
		}
	} else {
		const kp = "kprobe/"
		if len(section) > len(kp) && section[:len(kp)] == kp {
			l, err = link.Kprobe(section[len(kp):], prog, nil)
		} else {
			return fmt.Errorf("unsupported section %s", section)
		}
	}
	if err != nil {
		return err
	}
	pinnedLinks = append(pinnedLinks, l)
	return nil
}
